name: Jekyll site CI

on: Run command FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: Process completed with exit code 0
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: github.copilot.chat.summarizeAgentConversationHistory.enabled
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
